model:
  num_bins: 5
  num_encoders: 3
  base_num_channels: 32
  num_residual_blocks: 2
  skip_type: sum
  norm: BN
  upsampling: transposed
  use_upsample_conv: False
  recurrent_block: convlstm
  kernel_size: 3

train:
  save_dir: ./logs/20251028/e2vid_model/
  dataroot: /mnt/D/baichenxu/datasets/ecoco_depthmaps_test
  num_iter: 30
  num_workers: 8
  batch_size: 2
  num_epochs: 160
  weight_decay: 0.0
  grad_clip: 1.0
  save_freq: 10
  val_freq: 5
  grad_log_every: 50

  lr_e2vid: 1e-4
  l1_weight: 0.0
  lpips_weight: 1.0
  tc_weight: 5.0
  tc_alpha: 50.0
